---
title: "estimationResults"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
options(scipen = 999999)

library(dplyr)
library(TTR)
library(Rcpp)
library(knitr)
library(kableExtra)
library(fBasics)

source("../src/fun-getEstimatorsFromResults.R")
source("../src/fun-getStandardEstimators.R")
source("../src/fun-getRealizedVarianceSeries.R")
source("../src/fun-getHistoricalVarianceSeries.R")
source("../src/fun-getModelParameters.R")
source("../src/fun-getSchemeParameters.R")

tableRowNames <- c("gamma", "alpha", "beta", "eta", "delta", "kappa", "nu")
```

```{r read}
SPXMins_withEta40 <- readRDS("../results/SPXMins_withEta40.Rds")
SPXMins_withEta80 <- readRDS("../results/SPXMins_withEta80.Rds")
SPXMins_withEta120 <- readRDS("../results/SPXMins_withEta120.Rds")
SPXMins_withEta160 <- readRDS("../results/SPXMins_withEta160.Rds")
SPXMins_withEta200 <- readRDS("../results/SPXMins_withEta200.Rds")
SPXMins_withEta240 <- readRDS("../results/SPXMins_withEta240.Rds")
SPXMins_withEta280 <- readRDS("../results/SPXMins_withEta280.Rds")
SPXMins_withEta320 <- readRDS("../results/SPXMins_withEta320.Rds")
SPXMins_withEta360 <- readRDS("../results/SPXMins_withEta360.Rds")
SPXMins_withEta400 <- readRDS("../results/SPXMins_withEta400.Rds")

SPXMin <- readRDS("../data/SPX_min_fixed.Rds")
```

```{r}
estimators <- bind_cols(SPX40 = getEstimatorsFromResults(SPXMins_withEta40, 1 / (252 * 405)),
                        SPX80 = getEstimatorsFromResults(SPXMins_withEta80, 1 / (252 * 405)),
                        SPX120 = getEstimatorsFromResults(SPXMins_withEta120, 1 / (252 * 405)),
                        SPX160 = getEstimatorsFromResults(SPXMins_withEta160, 1 / (252 * 405)),
                        SPX200 = getEstimatorsFromResults(SPXMins_withEta200, 1 / (252 * 405)),
                        SPX240 = getEstimatorsFromResults(SPXMins_withEta240, 1 / (252 * 405)),
                        SPX280 = getEstimatorsFromResults(SPXMins_withEta280, 1 / (252 * 405)),
                        SPX320 = getEstimatorsFromResults(SPXMins_withEta320, 1 / (252 * 405)),
                        SPX360 = getEstimatorsFromResults(SPXMins_withEta360, 1 / (252 * 405)),
                        SPX400 = getEstimatorsFromResults(SPXMins_withEta400, 1 / (252 * 405))) %>%
  as.data.frame()

estimatorsRV <- bind_cols(RVH = getStandardEstimators(getRealizedVarianceSeries(SPXMin$adjRate, 60, 1 / (252 * 405)),
                                                      SPXMin$adjRate,
                                                      1 / (252 * 405)),
                          RVD = getStandardEstimators(getRealizedVarianceSeries(SPXMin$adjRate, 405, 1 / (252 * 405)),
                                                  SPXMin$adjRate,
                                                  1 / (252 * 405)),
                          RVW = getStandardEstimators(getRealizedVarianceSeries(SPXMin$adjRate, 2025, 1 / (252 * 405)),
                                                  SPXMin$adjRate,
                                                  1 / (252 * 405)),
                          RvM = getStandardEstimators(getRealizedVarianceSeries(SPXMin$adjRate, 8505, 1 / (252 * 405)),
                                                  SPXMin$adjRate,
                                                  1 / (252 * 405))) %>%
  as.data.frame()

row.names(estimators)   <- tableRowNames
row.names(estimatorsRV) <- tableRowNames

estimators %>%
  kable(caption = "SPX Estimators",
        col.names = c("40", "80", "120", "60", "200",
                      "240", "280", "320", "360", "400"),
        digits = 3)

estimatorsRV %>%
  kable(caption = "SPX Estimators",
        col.names = c("RVH", "RVD", "RVW", "RVM"),
        digits = 3)

```
