---
title: "SPX Option Pricing"
output:
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
options(scipen = 999999)

library(dplyr)
library(TTR)
library(Rcpp)
library(knitr)
library(kableExtra)
library(ggplot2)
library(reshape2)
library(ggthemes)
library(gtable)
library(gridExtra)   

strikes <- seq(from = 2025, to = 2975, by = 25)

impliedVol        <- readRDS("../results/impliedVolatility/impliedVol.Rds")[-c(1, 41), ]
impliedVolCIUpper <- readRDS("../results/impliedVolatility/impliedVolCIUpper.Rds")[-c(1, 41), ]
impliedVolCILower <- readRDS("../results/impliedVolatility/impliedVolCILower.Rds")[-c(1, 41), ]

optPrice        <- readRDS("../results/optPrice.Rds")[-c(1, 41), ]
optPriceCIUpper <- readRDS("../results/optPriceCIUpper.Rds")[-c(1, 41), ]
optPriceCILower <- readRDS("../results/optPriceCILower.Rds")[-c(1, 41), ]

blackScholesPrices <- readRDS("../results/blackScholesPrices.Rds")[-c(1, 41), ]

marketOptionQuotes <- readRDS("../data/marketOptionQuotes.Rds") %>%
  left_join(blackScholesPrices,
            by = "strike") %>%
  filter(!is.na(price))

```

## Implied Volatility

```{r, fig.width=15, fig.height=5}

data.frame(strike = strikes,
           MCMC40   = impliedVol[, 1],
           MCMC80   = impliedVol[, 2],
           MCMC120   = impliedVol[, 3],
           MCMC160   = impliedVol[, 4],
           MCMC200   = impliedVol[, 5],
           MCMC240   = impliedVol[, 6],
           MCMC280   = impliedVol[, 7],
           MCMC320   = impliedVol[, 8],
           MCMC360   = impliedVol[, 9],
           MCMC400   = impliedVol[, 10],
           RVD       = impliedVol[, 11],
           RVW       = impliedVol[, 12],
           RVM       = impliedVol[, 13],
           BS        = rep(0.1576664, 39),
           rynek     = marketOptionQuotes %>%
             arrange(strike) %>%
             select(implied_vol_source) %>%
             pull()) %>%
  melt(id="strike") %>%
    ggplot(., aes(x = strike, y = value, colour = variable)) +
  geom_line() +
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "zmienność implikowana",
       x = "cena wykonania") -> implVol

data.frame(strike = strikes,
           MCMC40   = impliedVol[, 1],
           MCMC80   = impliedVol[, 2],
           MCMC120   = impliedVol[, 3],
           MCMC160   = impliedVol[, 4],
           MCMC200   = impliedVol[, 5],
           MCMC240   = impliedVol[, 6],
           MCMC280   = impliedVol[, 7],
           MCMC320   = impliedVol[, 8],
           MCMC360   = impliedVol[, 9],
           MCMC400   = impliedVol[, 10],
           rynek     = marketOptionQuotes %>%
             arrange(strike) %>%
             select(implied_vol_source) %>%
             pull()) %>%
  melt(id="strike") %>%
    ggplot(., aes(x = strike, y = value, colour = variable)) +
  geom_line() + 
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "zmienność implikowana",
       x = "cena wykonania") +
  ylim(0, 0.75)-> implVol2

grid.arrange(implVol, implVol2, nrow = 1)
```

## Prices

```{r, fig.width=15, fig.height=5}

data.frame(strike = strikes,
          MCMC40   = optPrice[, 1],
           MCMC40sd = (optPriceCIUpper[, 1] - optPrice[, 1]) / 1.96,
           MCMC80   = optPrice[, 2],
           MCMC80sd = (optPriceCIUpper[, 2] - optPrice[, 2]) / 1.96,
           MCMC120   = optPrice[, 3],
           MCMC120sd = (optPriceCIUpper[, 3] - optPrice[, 3]) / 1.96,
           MCMC160   = optPrice[, 4],
           MCMC160sd = (optPriceCIUpper[, 4] - optPrice[, 4]) / 1.96,
           MCMC200   = optPrice[, 5],
           MCMC200sd = (optPriceCIUpper[, 5] - optPrice[, 5]) / 1.96,
           MCMC240   = optPrice[, 6],
           MCMC240sd = (optPriceCIUpper[, 6] - optPrice[, 6]) / 1.96,
           MCMC280   = optPrice[, 7],
           MCMC280sd = (optPriceCIUpper[, 7] - optPrice[, 7]) / 1.96,
           MCMC320   = optPrice[, 8],
           MCMC320sd = (optPriceCIUpper[, 8] - optPrice[, 8]) / 1.96,
           MCMC360   = optPrice[, 9],
           MCMC360sd = (optPriceCIUpper[, 9] - optPrice[, 9]) / 1.96,
           MCMC400   = optPrice[, 10],
           MCMC400sd = (optPriceCIUpper[, 10] - optPrice[, 10]) / 1.96,
           RVD       = optPrice[, 11],
           RVDsd     = (optPriceCIUpper[, 11] - optPrice[, 11]) / 1.96,
           RVW       = optPrice[, 12],
           RVWsd     = (optPriceCIUpper[, 12] - optPrice[, 12]) / 1.96,
           RVM       = optPrice[, 13],
           RVMsd     = (optPriceCIUpper[, 13] - optPrice[, 13]) / 1.96,
           BS        = blackScholesPrices %>%
             select(price) %>%
             pull(),
           rynek     = marketOptionQuotes %>%
             arrange(strike) %>%
             filter(strike >= 2000 & strike <= 3000) %>%
             select(mid_price) %>%
             pull()) -> priceTable

priceTable[, c(1, 2* (1:14), 29)] %>%
  melt(id="strike") %>%
    ggplot(., aes(x = strike, y = value, colour = variable)) +
  geom_line() +
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "cena",
       x = "cena wykonania") -> price

priceTable[, c(1, 2* (1:10), 29)]  %>%
  melt(id="strike") %>%
  ggplot(., aes(x = strike, y = value, colour = variable)) +
  geom_line() + 
  theme_bw() +
  theme(legend.title = element_blank()) +
  labs(y = "cena",
       x = "cena wykonania") -> price2

grid.arrange(price, price2, nrow = 1)
```


## Price table
```{r}
priceTable[, c(1, 2* (1:14), 29)] %>%
  kable("latex",
        booktabs = T,
        caption = "Prices",
        digits = 2) %>%
  kable_styling(font_size = 8)

priceTable[, c(1, 2 * (1:13) + 1)] %>%
  kable("latex",
        booktabs = T,
        caption = "Prices stdev",
        digits = 5) %>%
  kable_styling(font_size = 8)

cbind(priceTable[, 1],
          impliedVol) %>%
  kable("latex",
        booktabs = T,
        caption = "Implied vol",
        digits = 5) %>%
  kable_styling(font_size = 8)

cbind(priceTable[, 1],
          impliedVolCIUpper) %>%
  kable("latex",
        booktabs = T,
        caption = "Implied vol CI Upper",
        digits = 5) %>%
  kable_styling(font_size = 8)

cbind(priceTable[, 1],
          impliedVolCILower) %>%
  kable("latex",
        booktabs = T,
        caption = "Implied vol CI Lower",
        digits = 5) %>%
  kable_styling(font_size = 8)
```